import SEO, { breadcrumbJsonLd } from '../lib/seo'
import PageHero from '../components/shared/PageHero'
import { Section, SectionHeading, IconFeatureGrid, StepList } from '../components/shared/Section'
import Button from '../components/shared/Button'
import { Percent, Link2, BarChart3, Wallet, UserPlus, Share2, Users, Banknote } from 'lucide-react'

const TRADE_URL = import.meta.env.VITE_TRADE_URL || 'https://trade.coinbidex.com'

const REASONS = [
  { icon: Percent, title: 'Up to 50% commission', body: 'Earn a lifetime share of the trading fees your referrals generate.' },
  { icon: Link2, title: 'Custom tracking links', body: 'Generate unique referral links and codes for every campaign or channel.' },
  { icon: BarChart3, title: 'Real-time dashboard', body: 'Track clicks, sign-ups, and earnings in one place, updated live.' },
  { icon: Wallet, title: 'Monthly payouts', body: 'Commissions are paid out monthly directly to your CoinBidex wallet.' },
]

const STEPS = [
  { icon: UserPlus, title: 'Join the program', body: 'Sign up for the Affiliate Program from your dashboard — approval is instant.' },
  { icon: Share2, title: 'Share your link', body: 'Promote your unique referral link across your audience or content.' },
  { icon: Users, title: 'They trade', body: 'Anyone who signs up through your link and trades generates commission for you.' },
  { icon: Banknote, title: 'Get paid', body: 'Commissions accrue in real time and pay out to your wallet every month.' },
]

export default function Affiliate() {
  return (
    <>
      <SEO
        title="Affiliate Program"
        description="Earn up to 50% commission on trading fees by referring new users to CoinBidex."
        path="/affiliate"
        jsonLd={breadcrumbJsonLd([{ name: 'Home', path: '/' }, { name: 'Affiliate Program', path: '/affiliate' }])}
      />

      <PageHero
        eyebrow="Affiliate Program"
        title="Earn by sharing what you already trade on"
        description="Get up to 50% of the trading fees generated by everyone you refer — for as long as they trade."
        breadcrumbs={[{ name: 'Home', path: '/' }, { name: 'Affiliate Program', path: '/affiliate' }]}
        actions={[{ label: 'Join the Program', props: { href: `${TRADE_URL}/affiliate`, size: 'lg' } }]}
      />

      <Section className="pt-0">
        <SectionHeading eyebrow="How it works" title="Four steps to your first payout" />
        <div className="mt-14"><StepList steps={STEPS} /></div>
      </Section>

      <Section className="bg-surface-50 border-t border-surface-100">
        <SectionHeading eyebrow="Why join" title="One of the most generous programs in crypto" />
        <div className="mt-14"><IconFeatureGrid items={REASONS} columns={4} /></div>
      </Section>

      <Section className="text-center">
        <Button href={`${TRADE_URL}/affiliate`} size="lg">Join the Affiliate Program</Button>
      </Section>
    </>
  )
}
